-- Update blog posts titles
UPDATE blog_posts SET title_en = 'Authentic Rio Experiences: Live Like a Local Carioca' WHERE slug = 'authentic-rio-experiences-live-like-a-carioca';
UPDATE blog_posts SET title_en = 'The Best Feijoada in Rio de Janeiro for Tourists' WHERE slug = 'best-feijoada-rio-de-janeiro-tourists';
UPDATE blog_posts SET title_en = 'Best Tours in Rio de Janeiro: A Perfect 3-Day Itinerary' WHERE slug = 'best-tours-in-rio-de-janeiro-for-3-days';
UPDATE blog_posts SET title_en = 'Rio''s Hidden Gems by Sea: Boat Tours Beyond the Beach' WHERE slug = 'beyond-the-beach-discovering-rios-hidden-gems-by-sea';
UPDATE blog_posts SET title_en = 'Top Boutique Hotels in Rio with Private Rooftop Views' WHERE slug = 'boutique-hotels-rio-rooftops-vista-privada';
UPDATE blog_posts SET title_en = 'Top Boutique Hotels in Rio with Private Rooftop Views' WHERE slug = 'boutique%E2%80%91hotels%E2%80%91rio%E2%80%91rooftops%E2%80%91vista%E2%80%91privada';
UPDATE blog_posts SET title_en = 'Búzios & Cabo Frio Guide: Rio''s Stunning Lake Region' WHERE slug = 'buzios-cabo-frio-regiao-dos-lagos';
UPDATE blog_posts SET title_en = 'The Ultimate Guide to Rio Carnival: Tickets & Blocos' WHERE slug = 'carnaval-rio-guia-definitivo';
UPDATE blog_posts SET title_en = 'Christ the Redeemer: How to Visit Without the Crowds' WHERE slug = 'christ-the-redeemer-without-the-crowds';
UPDATE blog_posts SET title_en = 'Rio de Janeiro Safety & Public Transport Guide' WHERE slug = 'dicas-seguranca-transporte-rio';
UPDATE blog_posts SET title_en = 'Ecotourism in Rio: A Guide to Tijuca Forest Nature' WHERE slug = 'ecotourism-tijuca-forest-rio-de-janeiro';
UPDATE blog_posts SET title_en = 'Free Hikes vs. Guided Tours in Rio: Which is Better?' WHERE slug = 'free-hikes-vs-guided-tours-rio';
UPDATE blog_posts SET title_en = 'Traditional Food in Rio: Must-Try Carioca Gastronomy' WHERE slug = 'gastronomia-carioca-pratos-tipicos';
UPDATE blog_posts SET title_en = 'Hiking in Rio: Premium Guide to Tijuca Forest Trails' WHERE slug = 'hiking-in-rio-a-premium-guide-to-tijuca-forest';
UPDATE blog_posts SET title_en = 'How Much Does a City Tour in Rio de Janeiro Cost?' WHERE slug = 'how-much-does-a-city-tour-in-rio-de-jane';
UPDATE blog_posts SET title_en = 'How to Buy Maracanã Tickets as a Foreigner (No Scams)' WHERE slug = 'how-to-buy-maracana-tickets-as-a-foreigner';
UPDATE blog_posts SET title_en = 'How to Find a Trustworthy, Scam-Free Tour Guide in Rio' WHERE slug = 'how-to-find-a-trustworthy-tour-guide-in-rio-de-janeiro-scam-free';
UPDATE blog_posts SET title_en = 'The Complete Guide to Getting Maracanã Match Tickets' WHERE slug = 'how-to-get-tickets-for-maracana-the-comp';
UPDATE blog_posts SET title_en = 'How to Hire a Safe Tour Guide in Rio Without Getting Scammed' WHERE slug = 'how-to-hire-a-safe-tour-guide-in-rio-de-janeiro-without-getting-scammed';
UPDATE blog_posts SET title_en = 'How to Visit Maracanã Safely: A Guide for Tourists' WHERE slug = 'how-to-visit-maracana-safely-tourists';
UPDATE blog_posts SET title_en = 'Is it Safe to Do a Favela Tour in Rocinha, Rio?' WHERE slug = 'is-it-safe-to-do-a-favela-tour-in-rocinh';
UPDATE blog_posts SET title_en = 'Luxury Travel in Rio de Janeiro: 5-Star VIP Experiences' WHERE slug = 'luxury-travel-rio-de-janeiro';
UPDATE blog_posts SET title_en = 'The Best Time to Visit Rio de Janeiro: Month-by-Month' WHERE slug = 'melhor-epoca-visitar-rio-de-janeiro';
UPDATE blog_posts SET title_en = 'The Best Free Viewpoints in Rio de Janeiro for Photos' WHERE slug = 'melhores-mirantes-gratuitos-rj';
UPDATE blog_posts SET title_en = 'The Best Hiking Trails in Rio de Janeiro for Epic Views' WHERE slug = 'melhores-trilhas-rio-de-janeiro';
UPDATE blog_posts SET title_en = 'Top 10 Things to Do in Rio de Janeiro You Can''t Miss' WHERE slug = 'o-que-fazer-no-rio-de-janeiro-10-experiencias-que-voce-nao-pode-perder';
UPDATE blog_posts SET title_en = 'The Green Rebirth: Tijuca Forest Reforestation History' WHERE slug = 'o-renascimento-verde-a-incrivel-historia-do-reflorestamento-da-floresta-da-tijuca';
UPDATE blog_posts SET title_en = 'Where to Eat in Rio: Top Restaurants & Food Markets' WHERE slug = 'onde-comer-no-rio-gastronomia';
UPDATE blog_posts SET title_en = 'Must-Do Tours and Attractions in Rio de Janeiro' WHERE slug = 'passeios-imperdiveis-rio-de-janeiro';
UPDATE blog_posts SET title_en = 'Pedra da Gávea Hike Guide: Tips, Safety & What to Pack' WHERE slug = 'pedra-da-gavea-hike-guide';
UPDATE blog_posts SET title_en = 'The Ultimate Guide to the Best Beaches in Rio de Janeiro' WHERE slug = 'praias-do-rio-de-janeiro';
UPDATE blog_posts SET title_en = 'Rio Beyond the Obvious: Secret Spots & Local Hideaways' WHERE slug = 'rio-alem-do-obvio-lugares-secretos';
UPDATE blog_posts SET title_en = 'Rio de Janeiro with Kids: A Family-Friendly Itinerary' WHERE slug = 'rio-de-janeiro-com-criancas-roteiro';
UPDATE blog_posts SET title_en = 'A Perfect 3-Day Rio de Janeiro Itinerary by a Local' WHERE slug = 'rio-de-janeiro-in-3-days-itinerary-by-a';
UPDATE blog_posts SET title_en = 'Rio Safety Guide for US & European Travelers' WHERE slug = 'rio-safety-guide-for-us-european-travelers';
UPDATE blog_posts SET title_en = 'Rocinha Favela Tour in Rio: Insightful & Safe Experience' WHERE slug = 'rocinha-favela-tour-rio-de-janeiro';
UPDATE blog_posts SET title_en = 'Best Rooftops in Ipanema with Stunning Ocean Views' WHERE slug = 'rooftops-ipanema-vista-mar-rio';
UPDATE blog_posts SET title_en = 'Best Rooftops in Ipanema with Stunning Ocean Views' WHERE slug = 'rooftops%E2%80%91ipanema%E2%80%91vista%E2%80%91mar%E2%80%91rio';
UPDATE blog_posts SET title_en = 'Exclusive Rooftops in Santa Teresa with Private Views' WHERE slug = 'rooftops-santa-teresa-rio-vistas-privadas';
UPDATE blog_posts SET title_en = 'Exclusive Rooftops in Santa Teresa with Private Views' WHERE slug = 'rooftops%E2%80%91santa%E2%80%91teresa%E2%80%91rio%E2%80%91vistas%E2%80%91privadas';
UPDATE blog_posts SET title_en = 'Planning a Quick Trip? 3-Day Itinerary for Rio de Janeiro' WHERE slug = 'roteiro-3-dias-rio-de-janeiro';
UPDATE blog_posts SET title_en = 'The Best 3-Day Travel Itinerary for Rio de Janeiro' WHERE slug = 'roteiro-de-3-dias-no-rio-de-janeiro';
UPDATE blog_posts SET title_en = 'Sports Tourism in Rio: Football, Surfing & Adventures' WHERE slug = 'sports-tourism-rio-de-janeiro';
UPDATE blog_posts SET title_en = 'Sustainability & Craftsmanship: The Soul of Tocorimé' WHERE slug = 'sustainability-and-craftsmanship-the-soul-of-the-tocorime';
UPDATE blog_posts SET title_en = 'The Best Private Rooftops & Views in Rio (No Crowds)' WHERE slug = 'the-best-private-rooftops-and-views-in-rio-avoid-the-crowds';
UPDATE blog_posts SET title_en = 'The Best Private Rooftops & Views in Rio (No Crowds)' WHERE slug = 'the%E2%80%91best%E2%80%91private%E2%80%91rooftops%E2%80%91and%E2%80%91views%E2%80%91in%E2%80%91rio%E2%80%91avoid%E2%80%91the%E2%80%91crowds';
UPDATE blog_posts SET title_en = 'Best Months to Visit Rio for Hiking & Outdoor Activities' WHERE slug = 'the-best-months-to-visit-rio-for-hiking-and-outdoor-activities';
UPDATE blog_posts SET title_en = 'Best Specialty Coffee Shops in Downtown Rio de Janeiro' WHERE slug = 'the-best-specialty-coffee-shops-in-the-center-of-rio-de-janeiro';
UPDATE blog_posts SET title_en = 'Maracanã Stadium History: Brazil''s Greatest Football Temple' WHERE slug = 'the-maracana-stadium-a-comprehensive-history-of-brazils-greatest-sporting-temple-and-its-connection-to-the-fifa-world-cup';
UPDATE blog_posts SET title_en = 'Things to Do in Rio de Janeiro When It Rains' WHERE slug = 'things-to-do-in-rio-de-janeiro-when-it-rains';
UPDATE blog_posts SET title_en = 'The Ultimate Guide to Hiking Trails in Rio de Janeiro' WHERE slug = 'trilhas-no-rio-de-janeiro';
UPDATE blog_posts SET title_en = 'A Special Day in Rio: Christ the Redeemer Tour Tips' WHERE slug = 'um-dia-especial-no-rio-cristo-redentor-t';
UPDATE blog_posts SET title_en = 'Watch a Match at Maracanã: Why You Shouldn''t Go Alone' WHERE slug = 'watch-a-match-at-maracana-why-you-shouldnt-go-alone';
UPDATE blog_posts SET title_en = 'What to Do in Rio When It Rains: Indoor Activities & Museums' WHERE slug = 'what-to-do-in-rio-when-it-rains';
UPDATE blog_posts SET title_en = 'What to Wear in Rio: Essential Packing for Beach & Hiking' WHERE slug = 'what-to-wear-hiking-and-beach-rio-de-janeiro';
UPDATE blog_posts SET title_en = 'Where to Watch the 2026 World Cup in Rio de Janeiro' WHERE slug = 'where-to-watch-the-2026-world-cup-in-rio';

-- Update tours titles
UPDATE tours SET title_en = 'Little Africa Tour in Rio: History, Culture & Resistance' WHERE slug = 'pequena-frica-experience-hist-ria-cultura-e-resist-ncia';
UPDATE tours SET title_en = 'Little Africa Tour in Rio: History, Culture & Resistance' WHERE slug = 'pequena%E2%80%91frica%E2%80%91experience%E2%80%91hist%E2%80%91ria%E2%80%91cultura%E2%80%91e-resist%E2%80%91ncia%E2%80%91no%E2%80%91cora%E2%80%91o-do%E2%80%91rio';
UPDATE tours SET title_en = 'Scuba Diving in Arraial do Cabo | Brazilian Caribbean' WHERE slug = 'scuba-diving-in-arraial-do-cabo';
UPDATE tours SET title_en = 'Rio Historical Center Walking Tour | Culture & Architecture' WHERE slug = 'tour-pe-centro-historico';
UPDATE tours SET title_en = 'Rio Historical Center Walking Tour | Culture & Architecture' WHERE slug = 'tour%E2%80%91pe%E2%80%91centro%E2%80%91historico';
