import { useEffect, useMemo } from "react";
import { Helmet } from "react-helmet-async";
import { Link } from "react-router-dom";
import { format } from "date-fns";
import { enUS, es, ptBR } from "date-fns/locale";
import { ArrowRight, Bus, CalendarDays, MapPin, ShieldCheck, Ticket, Users } from "lucide-react";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { Button } from "@/components/ui/button";
import { useLocale } from "@/contexts/LocaleContext";
import { useMatches } from "@/hooks/useMatches";
import { getMatchDateInRio } from "@/lib/dateUtils";
import { track } from "@/lib/analytics";
import { generateBreadcrumbsSchema, getCanonicalUrl, getHreflangLinks } from "@/utils/seo";
import heroImage from "@/assets/maracana-fans.webp";

const PATH = "/football-experiences-in-rio-de-janeiro";
const content = {
  pt: { title:"Experiências de Futebol no Rio de Janeiro | Tocorime Rio", description:"Planeje uma experiência de futebol no Rio com jogos confirmados, ingresso oficial, transporte e guia local. Veja Flamengo, Fluminense e o Maracanã.", eyebrow:"Futebol carioca para viajantes", h1:"Experiências de Futebol no Rio de Janeiro", lead:"Escolha uma partida confirmada e viva o futebol carioca com a logística organizada por um guia local — do hotel ao estádio e de volta.", calendar:"Ver jogos confirmados", plan:"Planejar pelo WhatsApp", next:"Próximas experiências disponíveis", nextLead:"Datas, adversários e valores vêm diretamente do calendário atual. Se uma partida ainda não foi confirmada, ela não aparece aqui.", availability:"Ver disponibilidade", allMatches:"Ver calendário completo", none:"Ainda não há partidas confirmadas disponíveis. Consulte o calendário ou fale conosco sobre as datas da sua viagem.", howTitle:"Como incluir futebol na sua viagem ao Rio", steps:[["Comece pelas datas","Confira quais partidas estão oficialmente confirmadas durante a sua estadia."],["Escolha a atmosfera","Clássicos, jogos de liga e noites continentais oferecem experiências diferentes."],["Reserve a experiência","Cada página de partida informa o que está disponível, o valor atual e o próximo passo."]], includedTitle:"Uma experiência pensada para visitantes", included:[["Ingresso oficial","A opção disponível é informada na página de cada partida."],["Logística acompanhada","Transporte e ponto de encontro são confirmados conforme a experiência escolhida."],["Contexto local","O guia ajuda você a entender clubes, cantos, rivalidades e costumes do estádio."],["Planejamento honesto","Não anunciamos partidas ou vagas que ainda não estejam confirmadas."]], guideTitle:"Maracanã, Flamengo, Fluminense e além", guideText:"O Maracanã é o principal palco, mas uma viagem de futebol ao Rio começa pela data e pelo calendário real. A melhor escolha depende de quais clubes jogam em casa, da competição, do horário e da disponibilidade publicada para cada partida.", guideCta:"Consultar calendário do Maracanã", finalTitle:"Quer encaixar um jogo no seu roteiro?", finalText:"Envie as datas da viagem e o número de pessoas. Indicaremos apenas experiências realmente disponíveis.", finalCta:"Falar com um guia local" },
  en: { title:"Football Experiences in Rio de Janeiro | Tocorime Rio", description:"Plan a football experience in Rio with confirmed fixtures, official tickets, transport and a local guide. See Flamengo, Fluminense and Maracanã.", eyebrow:"Rio football for travellers", h1:"Football Experiences in Rio de Janeiro", lead:"Choose a confirmed fixture and experience Rio football with a local guide handling the journey from your hotel to the stadium and back.", calendar:"See confirmed matches", plan:"Plan on WhatsApp", next:"Upcoming football experiences", nextLead:"Dates, opponents and prices come directly from the current fixture list. If a match is not confirmed yet, it will not appear here.", availability:"Check Availability", allMatches:"View full match calendar", none:"There are no confirmed experiences available yet. Check the calendar or tell us your travel dates.", howTitle:"How to add football to your Rio trip", steps:[["Start with your dates","See which fixtures are officially confirmed during your stay."],["Choose the atmosphere","Derbies, league fixtures and continental nights each feel different."],["Book the experience","Each match page shows what is available, the current price and the next step."]], includedTitle:"Designed for visitors to Rio", included:[["Official ticket","The available ticket option is stated on each individual match page."],["Guided logistics","Transport and meeting details are confirmed for the experience you choose."],["Local context","Your guide explains the clubs, chants, rivalries and stadium customs."],["Honest planning","We never advertise a fixture or availability before it is confirmed."]], guideTitle:"Maracanã, Flamengo, Fluminense and beyond", guideText:"Maracanã is Rio's main football stage, but planning starts with your dates and the real fixture list. The right experience depends on who is at home, the competition, kick-off time and the availability published for each match.", guideCta:"Check the Maracanã calendar", finalTitle:"Want to fit a match into your itinerary?", finalText:"Send us your travel dates and group size. We will suggest only experiences that are genuinely available.", finalCta:"Talk to a local guide" },
  es: { title:"Experiencias de Fútbol en Río de Janeiro | Tocorime Rio", description:"Planifica una experiencia de fútbol en Río con partidos confirmados, entrada oficial, transporte y guía local. Vive Flamengo, Fluminense y Maracanã.", eyebrow:"Fútbol carioca para viajeros", h1:"Experiencias de Fútbol en Río de Janeiro", lead:"Elige un partido confirmado y vive el fútbol carioca con un guía local que organiza el trayecto desde tu hotel hasta el estadio y el regreso.", calendar:"Ver partidos confirmados", plan:"Planificar por WhatsApp", next:"Próximas experiencias disponibles", nextLead:"Las fechas, rivales y precios vienen directamente del calendario actual. Si un partido aún no está confirmado, no aparece aquí.", availability:"Ver disponibilidad", allMatches:"Ver calendario completo", none:"Aún no hay experiencias confirmadas disponibles. Consulta el calendario o envíanos las fechas de tu viaje.", howTitle:"Cómo incluir fútbol en tu viaje a Río", steps:[["Empieza por tus fechas","Comprueba qué partidos están oficialmente confirmados durante tu estancia."],["Elige el ambiente","Clásicos, partidos de liga y noches continentales ofrecen experiencias diferentes."],["Reserva la experiencia","Cada página muestra lo disponible, el precio actual y el siguiente paso."]], includedTitle:"Pensada para visitantes de Río", included:[["Entrada oficial","La opción disponible se indica en la página de cada partido."],["Logística acompañada","El transporte y el encuentro se confirman para la experiencia elegida."],["Contexto local","El guía explica clubes, cánticos, rivalidades y costumbres del estadio."],["Planificación honesta","Nunca anunciamos un partido o disponibilidad antes de su confirmación."]], guideTitle:"Maracanã, Flamengo, Fluminense y más", guideText:"Maracanã es el principal escenario, pero la planificación empieza con tus fechas y el calendario real. La mejor opción depende de quién juega en casa, la competición, el horario y la disponibilidad publicada.", guideCta:"Consultar calendario de Maracanã", finalTitle:"¿Quieres incluir un partido en tu itinerario?", finalText:"Envíanos las fechas del viaje y el número de personas. Solo recomendaremos experiencias realmente disponibles.", finalCta:"Hablar con un guía local" }
} as const;

export default function FootballExperiencesRio() {
  const { language, formatPrice } = useLocale();
  const { data: matches, isLoading } = useMatches();
  const lang = language === "pt" || language === "es" ? language : "en";
  const text = content[lang];
  const locale = lang === "pt" ? ptBR : lang === "es" ? es : enUS;
  const upcoming = useMemo(() => (matches || []).filter((match) => match.status === "available" && getMatchDateInRio(match.match_date) >= new Date() && match.home_team?.trim() && match.away_team?.trim()).slice(0, 3), [matches]);
  const whatsappText = lang === "pt" ? "Olá! Quero planejar uma experiência de futebol no Rio." : lang === "es" ? "¡Hola! Quiero planificar una experiencia de fútbol en Río." : "Hi! I want to plan a football experience in Rio.";
  const whatsappUrl = `https://wa.me/5521970702523?text=${encodeURIComponent(whatsappText)}`;
  useEffect(() => { track("view_tour", { tour_name: "Football Experiences in Rio de Janeiro", page_path: PATH }); }, []);
  const breadcrumbs = generateBreadcrumbsSchema([{ name: lang === "pt" ? "Início" : lang === "es" ? "Inicio" : "Home", url: getCanonicalUrl("/") }, { name: text.h1, url: getCanonicalUrl(PATH) }]);

  return <div className="min-h-screen bg-background">
    <Helmet><html lang={lang === "pt" ? "pt-BR" : lang} /><title>{text.title}</title><meta name="description" content={text.description} /><link rel="canonical" href={getCanonicalUrl(PATH)} />{getHreflangLinks(PATH).map((item) => <link key={item.hreflang} rel="alternate" hrefLang={item.hreflang} href={item.href} />)}<meta property="og:type" content="website" /><meta property="og:url" content={getCanonicalUrl(PATH)} /><meta property="og:title" content={text.title} /><meta property="og:description" content={text.description} /><meta property="og:image" content={getCanonicalUrl("/maracana-fans.jpg")} /><meta name="twitter:card" content="summary_large_image" /><meta name="twitter:title" content={text.title} /><meta name="twitter:description" content={text.description} /><meta name="twitter:image" content={getCanonicalUrl("/maracana-fans.jpg")} /><script type="application/ld+json">{JSON.stringify(breadcrumbs)}</script></Helmet>
    <Header />
    <main>
      <section className="relative flex h-[82vh] min-h-[620px] max-h-[820px] items-end overflow-hidden"><img src={heroImage} alt="Football supporters inside Maracanã Stadium in Rio de Janeiro" className="absolute inset-0 h-full w-full object-cover" fetchPriority="high" /><div className="absolute inset-0 bg-gradient-to-t from-primary via-primary/65 to-primary/10" /><div className="relative z-10 mx-auto w-full max-w-7xl px-4 pb-12 sm:px-6 sm:pb-16 lg:px-8"><p className="mb-4 text-sm font-semibold uppercase tracking-widest text-primary-foreground/80">{text.eyebrow}</p><h1 className="max-w-4xl text-4xl font-bold leading-tight text-primary-foreground sm:text-6xl lg:text-7xl">{text.h1}</h1><p className="mt-5 max-w-2xl text-base leading-relaxed text-primary-foreground/90 sm:text-lg">{text.lead}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg" className="bg-accent text-accent-foreground hover:bg-accent/90"><a href="#confirmed-matches">{text.calendar}<ArrowRight /></a></Button><Button asChild size="lg" variant="outline" className="border-primary-foreground/60 bg-primary/20 text-primary-foreground hover:bg-primary-foreground hover:text-primary"><a href={whatsappUrl} target="_blank" rel="noopener noreferrer">{text.plan}</a></Button></div></div></section>
      <section id="confirmed-matches" className="border-b border-border py-16 sm:py-20" data-football-experiences><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-widest text-accent">{text.calendar}</p><h2 className="mt-3 text-3xl font-bold sm:text-5xl">{text.next}</h2><p className="mt-4 leading-relaxed text-muted-foreground">{text.nextLead}</p></div>{isLoading ? <div className="mt-10 grid gap-5 md:grid-cols-3">{[0,1,2].map((item) => <div key={item} className="h-56 animate-pulse rounded-md bg-muted" />)}</div> : upcoming.length ? <div className="mt-10 grid gap-5 md:grid-cols-3">{upcoming.map((match) => { const date = getMatchDateInRio(match.match_date); return <article key={match.id} className="flex min-h-64 flex-col border-t-4 border-accent bg-card p-6 shadow-sm"><p className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">{match.competition || "Rio football"}</p><h3 className="mt-4 text-2xl font-bold">{match.home_team} <span className="text-muted-foreground">vs</span> {match.away_team}</h3><div className="mt-5 space-y-2 text-sm text-muted-foreground"><p className="flex items-center gap-2"><CalendarDays className="h-4 w-4 text-accent" />{format(date, lang === "pt" ? "dd 'de' MMMM, HH:mm" : "MMMM d, HH:mm", { locale })}</p><p className="flex items-center gap-2"><MapPin className="h-4 w-4 text-accent" />{match.stadium || match.venue || "Maracanã"}</p></div><div className="mt-auto flex items-end justify-between gap-4 pt-6"><p className="font-semibold text-primary">{formatPrice(match.price)}</p><Button asChild size="sm"><Link to={`/match/${match.slug || match.id}`} onClick={() => track("click_check_availability", { match_id: match.id, page_path: PATH }, `football-experience:${match.id}`)}>{text.availability}<ArrowRight /></Link></Button></div></article>; })}</div> : <p className="mt-10 border-l-4 border-accent pl-5 text-muted-foreground">{text.none}</p>}<Button asChild variant="outline" className="mt-8"><Link to="/maracana-calendario">{text.allMatches}<ArrowRight /></Link></Button></div></section>
      <section className="py-16 sm:py-24"><div className="mx-auto grid max-w-7xl gap-12 px-4 sm:px-6 lg:grid-cols-[0.8fr_1.2fr] lg:px-8"><div><p className="text-sm font-semibold uppercase tracking-widest text-accent">Rio match planning</p><h2 className="mt-3 text-3xl font-bold sm:text-5xl">{text.howTitle}</h2></div><ol className="divide-y divide-border border-y border-border">{text.steps.map(([title, description], index) => <li key={title} className="grid grid-cols-[3rem_1fr] gap-4 py-6"><span className="text-2xl font-bold text-accent">0{index+1}</span><div><h3 className="text-xl font-bold">{title}</h3><p className="mt-2 leading-relaxed text-muted-foreground">{description}</p></div></li>)}</ol></div></section>
      <section className="bg-primary py-16 text-primary-foreground sm:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><h2 className="max-w-3xl text-3xl font-bold sm:text-5xl">{text.includedTitle}</h2><div className="mt-10 grid gap-px bg-primary-foreground/20 sm:grid-cols-2 lg:grid-cols-4">{text.included.map(([title, description], index) => { const Icon = [Ticket, Bus, Users, ShieldCheck][index]; return <div key={title} className="bg-primary p-6"><Icon className="h-6 w-6 text-accent" /><h3 className="mt-5 text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-relaxed text-primary-foreground/70">{description}</p></div>; })}</div></div></section>
      <section className="py-16 sm:py-24"><div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8"><h2 className="text-3xl font-bold sm:text-5xl">{text.guideTitle}</h2><p className="mt-5 text-lg leading-relaxed text-muted-foreground">{text.guideText}</p><Button asChild variant="link" className="mt-4 h-auto p-0 text-base"><Link to="/maracana-calendario">{text.guideCta}<ArrowRight /></Link></Button></div></section>
      <section className="border-t border-border bg-secondary/10 py-16 sm:py-20"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 px-4 sm:px-6 lg:flex-row lg:items-end lg:px-8"><div className="max-w-3xl"><h2 className="text-3xl font-bold sm:text-5xl">{text.finalTitle}</h2><p className="mt-4 text-muted-foreground">{text.finalText}</p></div><Button asChild size="lg" className="shrink-0 bg-accent text-accent-foreground hover:bg-accent/90"><a href={whatsappUrl} target="_blank" rel="noopener noreferrer">{text.finalCta}<ArrowRight /></a></Button></div></section>
    </main><Footer />
  </div>;
}
