import * as z from "zod";

export const jsonFieldItemSchema = z.object({
  time: z.string().optional(),
  description: z.string().optional(),
  text: z.string().optional(),
  q: z.string().optional(),
  a: z.string().optional(),
  icon: z.string().optional(),
});

export const tourSchema = z.object({
  id: z.string().optional(),
  title: z.string().min(1, "Título é obrigatório"),
  short_description: z.string().optional().default(""),
  price: z.number().min(0).default(0),
  duration: z.string().optional().default(""),
  max_group_size: z.number().min(1).default(1),
  image_url: z.string().optional().default(""),
  is_featured: z.boolean().default(false),
  category: z.string().default("CITY TOUR"),
  is_active: z.boolean().default(true),
  sort_order: z.number().default(0),
  itinerary_json: z.array(jsonFieldItemSchema).optional().default([]),
  included_json: z.array(jsonFieldItemSchema).optional().default([]),
  highlights_json: z.array(jsonFieldItemSchema).optional().default([]),
  faq_json: z.array(jsonFieldItemSchema).optional().default([]),
  slug: z.string().optional(),
  title_en: z.string().optional().default(""),
  title_es: z.string().optional().default(""),
  short_description_en: z.string().optional().default(""),
  short_description_es: z.string().optional().default(""),
  category_en: z.string().optional().default(""),
  category_es: z.string().optional().default(""),
  itinerary_json_en: z.array(jsonFieldItemSchema).optional().default([]),
  itinerary_json_es: z.array(jsonFieldItemSchema).optional().default([]),
  included_json_en: z.array(jsonFieldItemSchema).optional().default([]),
  included_json_es: z.array(jsonFieldItemSchema).optional().default([]),
  highlights_json_en: z.array(jsonFieldItemSchema).optional().default([]),
  highlights_json_es: z.array(jsonFieldItemSchema).optional().default([]),
  faq_json_en: z.array(jsonFieldItemSchema).optional().default([]),
  faq_json_es: z.array(jsonFieldItemSchema).optional().default([]),
  images_json: z.array(z.string()).optional().default([]),
  difficulty: z.string().optional().default("Leve"),
  difficulty_en: z.string().optional().default(""),
  difficulty_es: z.string().optional().default(""),
  meeting_point_address: z.string().optional().default(""),
  meeting_point_address_en: z.string().optional().default(""),
  meeting_point_address_es: z.string().optional().default(""),
  youtube_video_url: z.string().optional().default(""),
  external_url: z.string().optional().default(""),
  pricing_model: z.enum(['fixed', 'dynamic', 'group', 'custom']).default('fixed'),
  price_1_person: z.number().optional().default(0),
  price_2_people: z.number().optional().default(0),
  price_3_6_people: z.number().optional().default(0),
  price_7_19_people: z.number().optional().default(0),
  available_days: z.array(z.string()).optional().default([]),
  has_morning: z.boolean().optional().default(false),
  has_afternoon: z.boolean().optional().default(false),
  has_night: z.boolean().optional().default(false),
  allows_private: z.boolean().optional().default(false),
  allows_open: z.boolean().optional().default(false),
  bares_diurnos: z.string().optional().default(""),
  bares_noturnos: z.string().optional().default(""),
});

export type TourFormValues = z.infer<typeof tourSchema>;
