// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-tours.ts
import { createClient } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_tours_default = defineTool({
  name: "list_tours",
  title: "List tours",
  description: "List active tours offered by Tocorime Rio (title, slug, category, price).",
  inputSchema: {
    category: z.string().optional().describe("Optional category filter (e.g. 'trilha', 'city-tour', 'um-dia')."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("tours").select("id, title, slug, category, price, is_active").eq("is_active", true).limit(limit ?? 50);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { tours: data }
    };
  }
});

// src/lib/mcp/tools/get-tour.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_tour_default = defineTool2({
  name: "get_tour",
  title: "Get tour details",
  description: "Fetch full details of a Tocorime Rio tour by its slug.",
  inputSchema: {
    slug: z2.string().min(1).describe("Tour slug (e.g. 'cachoeiras-horto').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("tours").select("*").eq("slug", slug).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No tour found with slug '${slug}'.` }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { tour: data }
    };
  }
});

// src/lib/mcp/tools/list-blog-posts.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_blog_posts_default = defineTool3({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List published Tocorime Rio blog posts (title, slug, language, published_at).",
  inputSchema: {
    language: z3.enum(["pt", "en"]).optional().describe("Filter by language."),
    limit: z3.number().int().min(1).max(100).optional().describe("Max rows to return (default 30).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ language, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser3(ctx).from("blog_posts").select("id, title, slug, language, published_at, meta_description").eq("is_published", true).order("published_at", { ascending: false }).limit(limit ?? 30);
    if (language) q = q.eq("language", language);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { posts: data }
    };
  }
});

// src/lib/mcp/tools/list-recent-sales.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.101.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_sales_default = defineTool4({
  name: "list_recent_sales",
  title: "List recent sales",
  description: "List the most recent sales/reservations. Admin-only: RLS returns rows only when the signed-in user has the admin role.",
  inputSchema: {
    only_paid: z4.boolean().optional().describe("If true, only paid sales are returned."),
    limit: z4.number().int().min(1).max(100).optional().describe("Max rows (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ only_paid, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser4(ctx).from("sales").select(
      "id, tour_title, customer_name, customer_email, quantity, total_price, selected_date, selected_period, is_paid, is_archived, created_at"
    ).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (only_paid) q = q.eq("is_paid", true);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { sales: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ogzasprtfgimjqrtcseg";
var mcp_default = defineMcp({
  name: "tocorime-rio-mcp",
  title: "Tocorime Rio MCP",
  version: "0.1.0",
  instructions: "Tools for the Tocorime Rio tourism site. Use `list_tours` / `get_tour` to explore active tours, `list_blog_posts` to browse published articles, and `list_recent_sales` for admin reservation data (returns rows only when the signed-in user is an admin).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_tours_default, get_tour_default, list_blog_posts_default, list_recent_sales_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
