
-- =========================================================
-- 1) NEW CLUSTER ARTICLE: Santa Teresa rooftops
-- =========================================================
INSERT INTO public.blog_posts (
  slug, title, excerpt, content,
  title_en, excerpt_en, content_en,
  image_url, is_published
) VALUES (
  'rooftops-santa-teresa-rio-vistas-privadas',
  'Rooftops em Santa Teresa: 5 vistas privadas do Rio com pôr do sol inesquecível',
  'Santa Teresa concentra as coberturas mais autênticas do Rio — bares escondidos, terraços de casarões e mirantes privados onde o pôr do sol vira espetáculo sem multidão.',
  '<p>Santa Teresa é o bairro que preserva o Rio de outros tempos: ruas de paralelepípedo, casarões coloniais e — talvez o segredo mais bem guardado — <strong>rooftops privados com vista para o Centro, a Baía de Guanabara e o Pão de Açúcar ao mesmo tempo</strong>.</p><p>Se você já leu nosso <a href="/blog/the-best-private-rooftops-and-views-in-rio-avoid-the-crowds">guia completo dos melhores rooftops privados do Rio</a>, este artigo aprofunda o bairro que mais concentra essas experiências.</p><h2>Por que Santa Teresa tem os melhores rooftops do Rio</h2><p>O bairro fica em um dos morros mais altos da zona central. Cada terraço vira, naturalmente, um mirante 360°. Diferente de Copacabana ou Ipanema, aqui os rooftops raramente têm fila — e quase todos aceitam reservas privadas.</p><h2>5 rooftops imperdíveis em Santa Teresa</h2><h3>1. Terraço do Parque das Ruínas</h3><p>Vista aberta para a Baía de Guanabara, entrada gratuita e um dos melhores pontos para pôr do sol da cidade.</p><h3>2. Mirante do Aprazível</h3><p>Restaurante com terraço debruçado sobre o Centro. Ideal para jantar ao entardecer.</p><h3>3. Cobertura do Hotel Santa Teresa Relais & Châteaux</h3><p>Rooftop de luxo com piscina, drinks autorais e vista privada — reserva obrigatória.</p><h3>4. Bar do Mineiro (terraço secreto)</h3><p>O boteco mais famoso do bairro tem um terraço nos fundos que poucos conhecem.</p><h3>5. Vista privada em atelier de artista</h3><p>Nosso passeio privado inclui acesso a um atelier com terraço fechado ao público — impossível de encontrar sozinho.</p><h2>Como visitar sem se perder</h2><p>Santa Teresa exige conhecer o bairro. Recomendamos combinar a visita com nosso <a href="/passeio/tour-pe-centro-historico">Tour a pé pelo Centro Histórico do Rio</a>, que termina exatamente aos pés do bairro.</p><h2>Continue explorando</h2><ul><li><a href="/blog/the-best-private-rooftops-and-views-in-rio-avoid-the-crowds">Guia completo: melhores rooftops e vistas privadas do Rio</a></li><li><a href="/blog/best-sunset-spots-rio-de-janeiro">Melhores pontos para pôr do sol no Rio</a></li></ul>',
  'Santa Teresa Rooftops: 5 Private Sunset Views in Rio You Won''t Find Alone',
  'Santa Teresa hides Rio''s most authentic rooftops — secret bar terraces, colonial mansion decks and private mirantes where sunset happens without the crowds.',
  '<p>Santa Teresa preserves an older Rio: cobblestone streets, colonial mansions, and — its best-kept secret — <strong>private rooftops with a simultaneous view of Downtown, Guanabara Bay and Sugarloaf</strong>.</p><p>If you already read our <a href="/blog/the-best-private-rooftops-and-views-in-rio-avoid-the-crowds">complete guide to the best private rooftops in Rio</a>, this article zooms into the single neighborhood that concentrates most of these experiences.</p><h2>Why Santa Teresa has Rio''s best rooftops</h2><p>The neighborhood sits on one of the highest hills in central Rio. Every terrace naturally becomes a 360° viewpoint. Unlike Copacabana or Ipanema, rooftops here rarely have queues — and almost all accept private reservations.</p><h2>5 must-visit rooftops in Santa Teresa</h2><h3>1. Parque das Ruínas terrace</h3><p>Wide-open view over Guanabara Bay, free entry, one of the best sunset spots in the city.</p><h3>2. Aprazível mirante</h3><p>Restaurant with a terrace hanging over Downtown Rio. Ideal for dinner at dusk.</p><h3>3. Hotel Santa Teresa Relais & Châteaux rooftop</h3><p>Luxury rooftop with pool, craft drinks, private view — booking required.</p><h3>4. Bar do Mineiro (secret back terrace)</h3><p>The neighborhood''s most famous boteco hides a back terrace few know about.</p><h3>5. Private artist studio rooftop</h3><p>Our private tour includes access to an artist''s studio with a closed-to-public rooftop — impossible to find alone.</p><h2>How to visit without getting lost</h2><p>Santa Teresa is best explored with someone who knows it. Consider pairing this with our <a href="/passeio/tour-pe-centro-historico">Rio Historic Centre Walking Tour</a>, which ends right at the base of the neighborhood.</p><h2>Keep exploring</h2><ul><li><a href="/blog/the-best-private-rooftops-and-views-in-rio-avoid-the-crowds">Full guide: best private rooftops and views in Rio</a></li><li><a href="/blog/best-sunset-spots-rio-de-janeiro">Best sunset spots in Rio de Janeiro</a></li></ul>',
  NULL, true
)
ON CONFLICT (slug) DO NOTHING;

-- =========================================================
-- 2) NEW CLUSTER ARTICLE: Ipanema oceanfront rooftops
-- =========================================================
INSERT INTO public.blog_posts (
  slug, title, excerpt, content,
  title_en, excerpt_en, content_en,
  image_url, is_published
) VALUES (
  'rooftops-ipanema-vista-mar-rio',
  'Rooftops em Ipanema com vista para o mar: bares e lounges exclusivos no Rio',
  'De Copacabana ao Arpoador, Ipanema concentra as coberturas com a melhor vista de mar do Rio. Mostramos os endereços que valem a reserva e os que fingem ter vista.',
  '<p>Todo rooftop em Ipanema promete vista de mar. Poucos entregam. Este guia lista as coberturas onde você realmente vê a orla — do Arpoador ao Leblon — sem esbarrar em prédio vizinho.</p><p>Para o panorama geral de coberturas privadas na cidade, veja também nosso <a href="/blog/the-best-private-rooftops-and-views-in-rio-avoid-the-crowds">guia completo dos rooftops privados do Rio</a>.</p><h2>O que faz um rooftop de Ipanema valer a pena</h2><p>Três coisas: (1) altura mínima do 10º andar, (2) fachada voltada para o mar sem obstrução, (3) reserva possível para grupo privado. Os endereços abaixo cumprem os três.</p><h2>Coberturas com vista real de mar</h2><h3>Emiliano Rio Rooftop</h3><p>Piscina no topo com vista para Copacabana. Um dos rooftops mais fotografados da cidade.</p><h3>Fasano Ipanema</h3><p>Piscina de borda infinita com vista para o Arpoador ao pôr do sol.</p><h3>Janeiro Hotel Rooftop (Leblon)</h3><p>Vista privada para Pedra da Gávea, Dois Irmãos e mar aberto.</p><h3>Hotel Arpoador — terraço secreto</h3><p>Menos famoso, mas com um dos melhores ângulos do Arpoador.</p><h2>Como reservar sem pagar caro</h2><p>Rooftops de hotel em Ipanema geralmente exigem consumação mínima ou hospedagem. Nossos guias organizam a reserva com antecedência — inclua isso no roteiro do <a href="/passeio/tour-pe-centro-historico">nosso tour privado pelo Rio</a>.</p><h2>Continue explorando</h2><ul><li><a href="/blog/the-best-private-rooftops-and-views-in-rio-avoid-the-crowds">Melhores rooftops privados do Rio (guia pillar)</a></li><li><a href="/blog/rooftops-santa-teresa-rio-vistas-privadas">Rooftops em Santa Teresa</a></li><li><a href="/blog/boutique-hotels-rio-rooftops-vista-privada">Rooftops de hotéis boutique no Rio</a></li></ul>',
  'Ipanema Rooftops with Ocean View: Rio''s Most Exclusive Rooftop Bars',
  'Every rooftop in Ipanema claims an ocean view — few deliver. Here are the addresses that truly overlook the beach, from Arpoador to Leblon.',
  '<p>Every rooftop in Ipanema advertises an ocean view. Few actually deliver. This guide lists the terraces where you really see the shoreline — from Arpoador to Leblon — without a neighboring building in the way.</p><p>For the full picture of private rooftops across the city, see our <a href="/blog/the-best-private-rooftops-and-views-in-rio-avoid-the-crowds">complete guide to private rooftops in Rio</a>.</p><h2>What makes an Ipanema rooftop worth it</h2><p>Three things: (1) at least a 10th-floor terrace, (2) unobstructed ocean-facing façade, (3) private booking available. The rooftops below check all three.</p><h2>Rooftops with a real ocean view</h2><h3>Emiliano Rio Rooftop</h3><p>Rooftop pool with Copacabana view. One of the most photographed rooftops in the city.</p><h3>Fasano Ipanema</h3><p>Infinity pool with Arpoador sunset view.</p><h3>Janeiro Hotel Rooftop (Leblon)</h3><p>Private view of Pedra da Gávea, Dois Irmãos and open ocean.</p><h3>Hotel Arpoador — secret terrace</h3><p>Less famous, one of the best angles of Arpoador.</p><h2>How to book without overpaying</h2><p>Ipanema hotel rooftops usually require minimum consumption or a stay. Our guides organize reservations in advance — bundle this into our <a href="/passeio/tour-pe-centro-historico">private Rio walking tour</a>.</p><h2>Keep exploring</h2><ul><li><a href="/blog/the-best-private-rooftops-and-views-in-rio-avoid-the-crowds">Best private rooftops in Rio (pillar guide)</a></li><li><a href="/blog/rooftops-santa-teresa-rio-vistas-privadas">Santa Teresa rooftops</a></li><li><a href="/blog/boutique-hotels-rio-rooftops-vista-privada">Rio boutique hotel rooftops</a></li></ul>',
  NULL, true
)
ON CONFLICT (slug) DO NOTHING;

-- =========================================================
-- 3) NEW CLUSTER ARTICLE: Boutique hotel rooftops
-- =========================================================
INSERT INTO public.blog_posts (
  slug, title, excerpt, content,
  title_en, excerpt_en, content_en,
  image_url, is_published
) VALUES (
  'boutique-hotels-rio-rooftops-vista-privada',
  'Rooftops em hotéis boutique do Rio: onde tomar drinks com vista privada',
  'Uma seleção dos hotéis boutique com as melhores coberturas do Rio — vista privada, piscinas de borda infinita e drinks autorais fora do circuito turístico.',
  '<p>Os melhores rooftops do Rio raramente estão nos hotéis maiores. Estão nos <strong>boutique hotels</strong> — endereços menores, com terraços privados e drinks pensados por bartenders locais.</p><p>Este artigo complementa nosso <a href="/blog/the-best-private-rooftops-and-views-in-rio-avoid-the-crowds">guia principal de rooftops privados do Rio</a>.</p><h2>O que caracteriza um rooftop boutique</h2><p>Menor lotação, curadoria de drinks, música ao vivo em alguns dias, e — o mais importante — vista privada sem circulação de turista de day-use.</p><h2>5 boutique hotels com rooftop imperdível</h2><h3>Hotel Santa Teresa Relais & Châteaux</h3><p>Piscina no topo com vista panorâmica sobre a Baía de Guanabara.</p><h3>Casa Marques Santa Teresa</h3><p>Terraço íntimo, menu de coquetéis com cachaça artesanal.</p><h3>Casa Mosquito (Ipanema)</h3><p>Rooftop com vista para o Cristo Redentor iluminado à noite.</p><h3>Yoo2 Rio de Janeiro (Botafogo)</h3><p>Piscina no topo com o melhor ângulo do Pão de Açúcar da cidade.</p><h3>Mama Ruisa (Santa Teresa)</h3><p>Terraço romântico, ideal para jantar ao entardecer.</p><h2>Combine com um passeio guiado</h2><p>Estes endereços ficam espalhados. Nosso <a href="/passeio/tour-pe-centro-historico">tour a pé pelo Centro Histórico</a> pode terminar com um drink em um dos rooftops de Santa Teresa.</p><h2>Continue explorando</h2><ul><li><a href="/blog/the-best-private-rooftops-and-views-in-rio-avoid-the-crowds">Guia pillar: rooftops privados no Rio</a></li><li><a href="/blog/rooftops-santa-teresa-rio-vistas-privadas">Rooftops em Santa Teresa</a></li><li><a href="/blog/rooftops-ipanema-vista-mar-rio">Rooftops em Ipanema</a></li></ul>',
  'Rio Boutique Hotel Rooftops: Where to Have Drinks with a Private View',
  'A curated list of Rio''s boutique hotels with the best private rooftops — infinity pools, curated cocktails, and views off the tourist trail.',
  '<p>Rio''s best rooftops rarely sit inside the biggest hotels. They live inside <strong>boutique hotels</strong> — smaller addresses with private terraces and drinks designed by local bartenders.</p><p>This article complements our <a href="/blog/the-best-private-rooftops-and-views-in-rio-avoid-the-crowds">main guide to private rooftops in Rio</a>.</p><h2>What defines a boutique rooftop</h2><p>Smaller crowd, curated drink menu, occasional live music, and — most importantly — a private view without day-use tourist traffic.</p><h2>5 boutique hotels with unmissable rooftops</h2><h3>Hotel Santa Teresa Relais & Châteaux</h3><p>Rooftop pool with panoramic Guanabara Bay view.</p><h3>Casa Marques Santa Teresa</h3><p>Intimate terrace, artisan cachaça cocktail menu.</p><h3>Casa Mosquito (Ipanema)</h3><p>Rooftop with a view of Christ the Redeemer lit at night.</p><h3>Yoo2 Rio de Janeiro (Botafogo)</h3><p>Rooftop pool with the city''s best angle on Sugarloaf.</p><h3>Mama Ruisa (Santa Teresa)</h3><p>Romantic terrace, ideal for sunset dinner.</p><h2>Combine with a guided tour</h2><p>These addresses are spread out. Our <a href="/passeio/tour-pe-centro-historico">Historic Centre walking tour</a> can end with a drink at one of Santa Teresa''s rooftops.</p><h2>Keep exploring</h2><ul><li><a href="/blog/the-best-private-rooftops-and-views-in-rio-avoid-the-crowds">Pillar guide: private rooftops in Rio</a></li><li><a href="/blog/rooftops-santa-teresa-rio-vistas-privadas">Santa Teresa rooftops</a></li><li><a href="/blog/rooftops-ipanema-vista-mar-rio">Ipanema rooftops</a></li></ul>',
  NULL, true
)
ON CONFLICT (slug) DO NOTHING;

-- =========================================================
-- 4) STRENGTHEN PILLAR — rooftops & "best views"
-- Append search-intent, FAQ (schema-friendly HTML) and cluster internal links
-- =========================================================
UPDATE public.blog_posts
SET
  content = content || '<hr/><h2>O que você realmente procura ao pesquisar "melhores vistas do Rio"</h2><p>Se você chegou aqui procurando por <em>"best views in Rio"</em>, <em>"rio de janeiro top view"</em> ou <em>"rooftops rio de janeiro"</em>, seu objetivo real costuma ser um destes três:</p><ul><li><strong>Vista privada sem multidão</strong> — evitar o circuito Cristo/Pão de Açúcar em horários lotados.</li><li><strong>Vista + experiência</strong> — combinar mirante com drink, jantar ou pôr do sol.</li><li><strong>Vista fotogênica</strong> — ângulos únicos para foto/vídeo que não aparecem no Instagram genérico.</li></ul><p>Este guia cobre os três. Abaixo, aprofundamos por tipo de experiência.</p><h2>Aprofunde por região (cluster de conteúdo)</h2><ul><li><a href="/blog/rooftops-santa-teresa-rio-vistas-privadas"><strong>Rooftops em Santa Teresa</strong></a> — o bairro mais alto do Rio central.</li><li><a href="/blog/rooftops-ipanema-vista-mar-rio"><strong>Rooftops em Ipanema com vista de mar</strong></a> — coberturas com orla real.</li><li><a href="/blog/boutique-hotels-rio-rooftops-vista-privada"><strong>Rooftops de hotéis boutique</strong></a> — vistas exclusivas fora do circuito turístico.</li></ul><h2>Perguntas frequentes</h2><h3>Qual é o melhor rooftop do Rio com vista privada?</h3><p>Depende do que você prioriza. Para vista 360° da cidade, o rooftop do Hotel Santa Teresa. Para vista de mar, Fasano Ipanema. Para vista do Cristo, Casa Mosquito.</p><h3>Os melhores mirantes do Rio são pagos?</h3><p>Não. Os mirantes públicos — Mirante Dona Marta, Parque das Ruínas, Vista Chinesa — são gratuitos e oferecem ângulos que rivalizam com os pagos.</p><h3>Qual a melhor hora para visitar um rooftop no Rio?</h3><p>De 30 a 45 minutos antes do pôr do sol. Você pega a luz dourada, o pôr do sol propriamente dito e a cidade acendendo à noite.</p><h3>Como visitar rooftops privados sem gastar muito?</h3><p>Muitos aceitam apenas consumação mínima. Nossos <a href="/passeio/tour-pe-centro-historico">passeios privados</a> incluem reserva antecipada com condições melhores.</p><h3>Rooftops no Rio são seguros à noite?</h3><p>Em bairros como Ipanema, Leblon e Santa Teresa, sim. Recomendamos chegar de aplicativo de transporte e sair da mesma forma.</p>',
  content_en = content_en || '<hr/><h2>What you actually want when you search "best views in Rio"</h2><p>If you landed here searching for <em>"best views in Rio"</em>, <em>"rio de janeiro top view"</em>, or <em>"rooftops rio de janeiro"</em>, your real goal is usually one of three:</p><ul><li><strong>A private view without crowds</strong> — skipping the Christ / Sugarloaf circuit at peak hours.</li><li><strong>View + experience</strong> — combining a viewpoint with drinks, dinner, or sunset.</li><li><strong>Photogenic angle</strong> — unique shots you won''t find on generic Instagram feeds.</li></ul><p>This guide covers all three. Below, we go deeper by type.</p><h2>Go deeper by neighborhood (content cluster)</h2><ul><li><a href="/blog/rooftops-santa-teresa-rio-vistas-privadas"><strong>Santa Teresa rooftops</strong></a> — the highest neighborhood in central Rio.</li><li><a href="/blog/rooftops-ipanema-vista-mar-rio"><strong>Ipanema oceanfront rooftops</strong></a> — terraces with a real shoreline view.</li><li><a href="/blog/boutique-hotels-rio-rooftops-vista-privada"><strong>Boutique hotel rooftops</strong></a> — exclusive views off the tourist trail.</li></ul><h2>Frequently asked questions</h2><h3>What is the best rooftop in Rio with a private view?</h3><p>Depends on your priority. For a 360° city view, the Hotel Santa Teresa rooftop. For ocean view, Fasano Ipanema. For a Christ the Redeemer view, Casa Mosquito.</p><h3>Are Rio''s best viewpoints paid?</h3><p>No. Public viewpoints — Mirante Dona Marta, Parque das Ruínas, Vista Chinesa — are free and rival any paid rooftop.</p><h3>When is the best time to visit a rooftop in Rio?</h3><p>30 to 45 minutes before sunset. You catch the golden light, sunset itself, and the city lighting up at night.</p><h3>How to visit private rooftops without overspending?</h3><p>Many accept minimum consumption only. Our <a href="/passeio/tour-pe-centro-historico">private tours</a> include advance booking with better conditions.</p><h3>Are rooftops in Rio safe at night?</h3><p>In Ipanema, Leblon and Santa Teresa, yes. Arrive and leave by rideshare.</p>',
  updated_at = now()
WHERE slug = 'the-best-private-rooftops-and-views-in-rio-avoid-the-crowds';

-- =========================================================
-- 5) STRENGTHEN "best sunset spots" post (ranks for "best places to watch sunset")
-- =========================================================
UPDATE public.blog_posts
SET
  content = content || '<hr/><h2>Intenção de busca: o que você espera de "melhores lugares para o pôr do sol"</h2><p>Você quer três coisas: (1) ângulo aberto sem obstrução, (2) fácil acesso — nem sempre trilha longa, (3) ambiente que aguente ficar 30 minutos depois do sol se pôr, quando a cidade acende.</p><h2>Perguntas frequentes</h2><h3>Qual é o melhor lugar para ver o pôr do sol no Rio?</h3><p>O Arpoador é o mais famoso. Para uma vista privada sem multidão, veja nosso <a href="/blog/the-best-private-rooftops-and-views-in-rio-avoid-the-crowds">guia de rooftops privados</a>.</p><h3>A que horas o sol se põe no Rio?</h3><p>Entre 17h30 (inverno) e 18h45 (verão). Chegue 45 minutos antes.</p><h3>Vale a pena pagar por um mirante?</h3><p>Os melhores são gratuitos. Rooftops pagos entregam experiência, não necessariamente vista superior.</p>',
  content_en = content_en || '<hr/><h2>Search intent: what you actually want from "best sunset spots"</h2><p>You want three things: (1) unobstructed open angle, (2) easy access — not always a long hike, (3) an environment that lets you stay 30 minutes after sunset when the city lights up.</p><h2>Frequently asked questions</h2><h3>What is the best place to watch the sunset in Rio?</h3><p>Arpoador is the most famous. For a private view without crowds, see our <a href="/blog/the-best-private-rooftops-and-views-in-rio-avoid-the-crowds">private rooftops guide</a>.</p><h3>What time does the sun set in Rio?</h3><p>Between 5:30pm (winter) and 6:45pm (summer). Arrive 45 minutes early.</p><h3>Is it worth paying for a viewpoint?</h3><p>The best ones are free. Paid rooftops offer experience, not necessarily a better view.</p>',
  updated_at = now()
WHERE slug = 'best-sunset-spots-rio-de-janeiro';

-- =========================================================
-- 6) OPTIMIZE TOUR "tour-pe-centro-historico" — target "historic centre" & "walking tour rio centro"
-- =========================================================
UPDATE public.tours
SET
  title = 'Rio Historic Centre Walking Tour: Colonial, Imperial & Modern Rio a Pé',
  title_en = 'Rio Historic Centre Walking Tour: Colonial, Imperial & Modern Rio on Foot',
  title_es = 'Tour a Pie por el Centro Histórico de Río: Colonial, Imperial y Moderno',
  short_description = 'Walking tour privado pelo Centro Histórico do Rio de Janeiro — uma imersão a pé pelo coração colonial, imperial e moderno da cidade. Você percorre o Theatro Municipal, a Biblioteca Nacional, o Real Gabinete Português de Leitura, o Largo da Carioca, palácios de outros séculos e cafeterias históricas, guiado por um especialista local que conecta cada esquina a uma história do Brasil.

Ideal para quem procura o "historic centre" autêntico do Rio — longe dos pontos turísticos óbvios, com paradas para café, arte e arquitetura. O passeio termina na base de Santa Teresa, permitindo continuar a experiência em um rooftop com vista privada da cidade.

Grupo pequeno, ritmo leve, foco em curadoria e narrativa. A melhor forma de entender por que o Rio é muito mais que praia.',
  short_description_en = 'Private walking tour of Rio de Janeiro''s historic centre — an on-foot immersion through the city''s colonial, imperial, and modern heart. Walk past the Theatro Municipal, the National Library, the Real Gabinete Português de Leitura, Largo da Carioca, centuries-old palaces, and historic coffee shops, guided by a local expert who ties every corner to a chapter of Brazilian history.

Ideal for travelers looking for Rio''s authentic historic centre — off the obvious tourist trail, with stops for coffee, art, and architecture. The tour ends at the base of Santa Teresa, so you can continue with a private rooftop drink overlooking the city.

Small group, easy pace, curated storytelling. The best way to understand why Rio is far more than beaches.',
  short_description_es = 'Tour a pie privado por el centro histórico de Río de Janeiro — una inmersión por el corazón colonial, imperial y moderno de la ciudad. Recorres el Theatro Municipal, la Biblioteca Nacional, el Real Gabinete Portugués de Lectura, el Largo da Carioca, palacios de otros siglos y cafeterías históricas, guiado por un experto local que conecta cada esquina con una historia de Brasil.

Ideal para quien busca el "historic centre" auténtico de Río — lejos de los puntos turísticos obvios, con paradas para café, arte y arquitectura. El tour termina al pie de Santa Teresa, para continuar con un drink en una azotea privada con vista de la ciudad.

Grupo pequeño, ritmo tranquilo, curaduría y narrativa. La mejor manera de entender por qué Río es mucho más que playa.',
  updated_at = now()
WHERE slug = 'tour-pe-centro-historico';
