UPDATE public.blog_posts SET
  title = 'Melhor Feijoada do Rio de Janeiro: 8 lugares que os cariocas amam (2026)',
  excerpt = 'Qual é a melhor feijoada do Rio de Janeiro? Guia com 8 restaurantes aprovados por cariocas, dias certos, preços e como pedir sem cair em armadilha para turista.',
  meta_description = 'Melhor feijoada do Rio de Janeiro: 8 restaurantes que os cariocas realmente frequentam, os melhores dias, preços e o que pedir para acompanhar.',
  meta_keywords_pt = 'melhor feijoada rio de janeiro, a melhor feijoada do rio de janeiro, qual a melhor feijoada do rio de janeiro, onde comer a melhor feijoada do rio de janeiro, feijoada rio de janeiro, feijoada no rio de janeiro, feijoada do rio de janeiro, restaurante feijoada rio, feijoada sábado rio de janeiro, ' || COALESCE(meta_keywords_pt,''),
  meta_keywords = 'best feijoada rio de janeiro, feijoada rio de janeiro, where to eat feijoada in rio, feijoada restaurant rio, ' || COALESCE(meta_keywords,''),
  meta_keywords_es = 'mejor feijoada rio de janeiro, dónde comer feijoada en rio, feijoada rio de janeiro, ' || COALESCE(meta_keywords_es,''),
  content = content || '<h2>Qual é a melhor feijoada do Rio de Janeiro?</h2><p>Se você quer uma resposta direta: a <strong>melhor feijoada do Rio de Janeiro</strong> é servida nos botequins tradicionais que cozinham o feijão no mesmo dia — em geral às quartas-feiras e aos sábados. Os endereços listados acima são os que os cariocas realmente frequentam, com caldo encorpado, carnes frescas, farofa na hora e couve refogada na banha.</p><h2>Perguntas frequentes sobre feijoada no Rio</h2><h3>Qual dia da semana tem feijoada no Rio de Janeiro?</h3><p>Sábado é o dia clássico da feijoada no Rio, e muitos botequins também servem às quartas-feiras. Restaurantes voltados a turistas oferecem todos os dias, mas costuma ser feijoada reaquecida.</p><h3>Quanto custa uma feijoada no Rio de Janeiro?</h3><p>Uma porção individual costuma variar entre R$ 60 e R$ 120, e as porções para duas pessoas ficam entre R$ 110 e R$ 200, dependendo do bairro e do restaurante.</p><h3>Onde comer a melhor feijoada do Rio de Janeiro sendo turista?</h3><p>Prefira botequins tradicionais na Lapa, em Santa Teresa, na Glória e no Centro. Pergunte sempre se a feijoada é feita na hora e evite casas com fotos do prato na porta.</p><h3>O que acompanha a feijoada?</h3><p>Arroz branco, couve refogada, farofa, laranja em rodelas e molho de pimenta. Para beber, chopp gelado ou caipirinha.</p><h3>Existe feijoada vegetariana no Rio?</h3><p>Sim. Vários restaurantes de Botafogo e Santa Teresa servem feijoada vegetariana com legumes defumados e tofu, geralmente aos sábados.</p>',
  content_en = COALESCE(content_en,'') || '<h2>Feijoada in Rio: quick FAQ</h2><h3>What day is feijoada served in Rio de Janeiro?</h3><p>Saturday is the classic feijoada day, and many botequins also cook it on Wednesdays.</p><h3>How much does feijoada cost in Rio?</h3><p>Expect R$60–120 per person, or R$110–200 for a two-person portion.</p><h3>Where should tourists eat feijoada in Rio?</h3><p>Traditional botequins in Lapa, Santa Teresa, Glória and Centro. Always ask if it was cooked the same day.</p>',
  content_es = COALESCE(content_es,'') || '<h2>Feijoada en Rio: preguntas frecuentes</h2><h3>¿Qué día se sirve feijoada en Rio de Janeiro?</h3><p>El sábado es el día clásico, y muchos botequins también la preparan los miércoles.</p><h3>¿Cuánto cuesta una feijoada en Rio?</h3><p>Entre R$60 y R$120 por persona; R$110–200 la porción para dos.</p><h3>¿Dónde comer la mejor feijoada siendo turista?</h3><p>En botequins tradicionales de Lapa, Santa Teresa, Glória y Centro. Pregunta siempre si fue hecha en el día.</p>',
  updated_at = now()
WHERE slug = 'best-feijoada-rio-de-janeiro-tourists';